apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: deaf-egret-go 
  janus-idp.io/tekton: deaf-egret-go
  backstage.io/kubernetes-id: deaf-egret-go
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: deaf-egret-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  