apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: deaf-egret-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: deaf-egret-go 
  name: deaf-egret-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: deaf-egret-go 
